/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Notez
 * OpenAPI spec version: 1.0.0
 */
import type { MetadataGroupFieldSchemaDto } from './metadataGroupFieldSchemaDto';
import type { MetadataGroupFieldDtoValue } from './metadataGroupFieldDtoValue';

export interface MetadataGroupFieldDto {
  id: string;
  schema: MetadataGroupFieldSchemaDto;
  value: MetadataGroupFieldDtoValue;
}
