/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Notez
 * OpenAPI spec version: 1.0.0
 */
import type { NoteMetadataDto } from './noteMetadataDto';
import type { NoteDtoDocument } from './noteDtoDocument';

export interface NoteDto {
  id: string;
  title: string;
  metadata: NoteMetadataDto;
  document: NoteDtoDocument;
  createdAt: string;
  updatedAt: string;
}
