/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Notez
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateMetadataFieldBody {
  fieldId: string;
  name: string;
  type: string;
}
