fragment AppIdeaMetadataField on MetadataGroupFieldEntry {
  id
  schema {
    id
    name
    type
    updatedAt
  }
  value {
    __typename

    ... on MetadataFieldTextValue {
      text
      type
      updatedAt
    } 

    ... on MetadataFieldNumberValue {
      number
      type
      updatedAt
    }

    ... on MetadataFieldDateValue {
      date
      type
      updatedAt
    }

    ... on MetadataFieldReferenceValue {
      reference {
        ...AppIdeaReference
      }
      type
      updatedAt
    }
  }
}