fragment AppIdeaMetadataField on MetadataGroupFieldEntry {
  id
  schema {
    id
    name
    type
    updatedAt
  }
  value {
    __typename

    ... on MetadataFieldTextValue {
      text
      updatedAt
    } 

    ... on MetadataFieldNumberValue {
      number
      updatedAt
    }

    ... on MetadataFieldDateValue {
      date
      updatedAt
    }
  }
}