fragment AppIdeaMetadataField on MetadataGroupFieldEntry {
  id
  schema {
    id
    name
    type
  }
  value {
    __typename
    
    ... on MetadataFieldTextValue {
      text
    } 

    ... on MetadataFieldNumberValue {
      number
    }

    ... on MetadataFieldDateValue {
      date
    }
  }
}