fragment AppIdea on Idea {
  id
  title
  document
  metadata {
    groups {
      ...AppIdeaMetadataGroup
    }
  }
  toReferences {
    ...AppIdeaReference
  }
  fromReferences {
    ...AppIdeaReference
  }
  createdAt
  updatedAt
  __typename
}

fragment AppIdeaMetadataGroup on MetadataGroup {
  context
  template {
    id
    title
  }
  fields {
    ...AppIdeaMetadataField
  }
}