fragment AppNote on Note {
  id
  title
  document
  metadata {
    groups {
      context
      fields {
        id
        schema {
          name
          type
        }
        value
      }
    }
  }
}
